---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: long-install
spec:
  chart:
    git: https://github.com/hiddeco/test-charts
    path: charts/long-install
  values:
    replicaCount: 1
