{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "children.serviceAccountName" . }}
  labels:
{{ include "children.labels" . | indent 4 }}
{{- end -}}
