dependencies:
  - name: redis
    version: 5.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: dependencies.redis.enabled
  - name: postgresql
    version: 6.5.0
    repository: dependencies.redis.enabled
    condition: dependencies.postgresql.enabled
